//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorTable.Components {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorTable.Components.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die False ähnelt.
        /// </summary>
        internal static string BooleanConditionFalse {
            get {
                return ResourceManager.GetString("BooleanConditionFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not null ähnelt.
        /// </summary>
        internal static string BooleanConditionIsNotNull {
            get {
                return ResourceManager.GetString("BooleanConditionIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is null ähnelt.
        /// </summary>
        internal static string BooleanConditionIsNull {
            get {
                return ResourceManager.GetString("BooleanConditionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die True ähnelt.
        /// </summary>
        internal static string BooleanConditionTrue {
            get {
                return ResourceManager.GetString("BooleanConditionTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is equal to ähnelt.
        /// </summary>
        internal static string CustomSelectConditionIsEqualTo {
            get {
                return ResourceManager.GetString("CustomSelectConditionIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not equal to ähnelt.
        /// </summary>
        internal static string CustomSelectConditionIsNotEqualTo {
            get {
                return ResourceManager.GetString("CustomSelectConditionIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not null ähnelt.
        /// </summary>
        internal static string CustomSelectConditionIsNotNull {
            get {
                return ResourceManager.GetString("CustomSelectConditionIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is null ähnelt.
        /// </summary>
        internal static string CustomSelectConditionIsNull {
            get {
                return ResourceManager.GetString("CustomSelectConditionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is equal to ähnelt.
        /// </summary>
        internal static string EnumConditionIsEqualTo {
            get {
                return ResourceManager.GetString("EnumConditionIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not equal to ähnelt.
        /// </summary>
        internal static string EnumConditionIsNotEqualTo {
            get {
                return ResourceManager.GetString("EnumConditionIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not null ähnelt.
        /// </summary>
        internal static string EnumConditionIsNotNull {
            get {
                return ResourceManager.GetString("EnumConditionIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is null ähnelt.
        /// </summary>
        internal static string EnumConditionIsNull {
            get {
                return ResourceManager.GetString("EnumConditionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string FilterManagerApply {
            get {
                return ResourceManager.GetString("FilterManagerApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        internal static string FilterManagerClear {
            get {
                return ResourceManager.GetString("FilterManagerClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string FilterManagerClose {
            get {
                return ResourceManager.GetString("FilterManagerClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is equal to ähnelt.
        /// </summary>
        internal static string NumberConditionIsEqualTo {
            get {
                return ResourceManager.GetString("NumberConditionIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is greater than ähnelt.
        /// </summary>
        internal static string NumberConditionIsGreaterThan {
            get {
                return ResourceManager.GetString("NumberConditionIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is greater than or equal to ähnelt.
        /// </summary>
        internal static string NumberConditionIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("NumberConditionIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is less than ähnelt.
        /// </summary>
        internal static string NumberConditionIsLessThan {
            get {
                return ResourceManager.GetString("NumberConditionIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is less than or equal to ähnelt.
        /// </summary>
        internal static string NumberConditionIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("NumberConditionIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not equal to ähnelt.
        /// </summary>
        internal static string NumberConditionIsnotEqualTo {
            get {
                return ResourceManager.GetString("NumberConditionIsnotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not null ähnelt.
        /// </summary>
        internal static string NumberConditionIsNotNull {
            get {
                return ResourceManager.GetString("NumberConditionIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is null ähnelt.
        /// </summary>
        internal static string NumberConditionIsNull {
            get {
                return ResourceManager.GetString("NumberConditionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First ähnelt.
        /// </summary>
        internal static string PagerFirst {
            get {
                return ResourceManager.GetString("PagerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last ähnelt.
        /// </summary>
        internal static string PagerLast {
            get {
                return ResourceManager.GetString("PagerLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string PagerNext {
            get {
                return ResourceManager.GetString("PagerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous ähnelt.
        /// </summary>
        internal static string PagerPrevious {
            get {
                return ResourceManager.GetString("PagerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contains ähnelt.
        /// </summary>
        internal static string StringConditionContains {
            get {
                return ResourceManager.GetString("StringConditionContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Does not contain ähnelt.
        /// </summary>
        internal static string StringConditionDoesNotContain {
            get {
                return ResourceManager.GetString("StringConditionDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ends with ähnelt.
        /// </summary>
        internal static string StringConditionEndsWith {
            get {
                return ResourceManager.GetString("StringConditionEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is equal to ähnelt.
        /// </summary>
        internal static string StringConditionIsEqualTo {
            get {
                return ResourceManager.GetString("StringConditionIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not equal to ähnelt.
        /// </summary>
        internal static string StringConditionIsNotEqualTo {
            get {
                return ResourceManager.GetString("StringConditionIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not null or empty ähnelt.
        /// </summary>
        internal static string StringConditionIsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("StringConditionIsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is null or empty ähnelt.
        /// </summary>
        internal static string StringConditionIsNullOrEmpty {
            get {
                return ResourceManager.GetString("StringConditionIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starts with ähnelt.
        /// </summary>
        internal static string StringConditionStartsWith {
            get {
                return ResourceManager.GetString("StringConditionStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details View ähnelt.
        /// </summary>
        internal static string TableDetailsView {
            get {
                return ResourceManager.GetString("TableDetailsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global Search... ähnelt.
        /// </summary>
        internal static string TableGlobalSearch {
            get {
                return ResourceManager.GetString("TableGlobalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading... ähnelt.
        /// </summary>
        internal static string TableLoading {
            get {
                return ResourceManager.GetString("TableLoading", resourceCulture);
            }
        }
    }
}
