//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorTable.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorTable.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string BooleanConditionFalse {
            get {
                return ResourceManager.GetString("BooleanConditionFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        internal static string BooleanConditionIsNotNull {
            get {
                return ResourceManager.GetString("BooleanConditionIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        internal static string BooleanConditionIsNull {
            get {
                return ResourceManager.GetString("BooleanConditionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string BooleanConditionTrue {
            get {
                return ResourceManager.GetString("BooleanConditionTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        internal static string CustomSelectConditionIsEqualTo {
            get {
                return ResourceManager.GetString("CustomSelectConditionIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        internal static string CustomSelectConditionIsNotEqualTo {
            get {
                return ResourceManager.GetString("CustomSelectConditionIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        internal static string CustomSelectConditionIsNotNull {
            get {
                return ResourceManager.GetString("CustomSelectConditionIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        internal static string CustomSelectConditionIsNull {
            get {
                return ResourceManager.GetString("CustomSelectConditionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        internal static string EnumConditionIsEqualTo {
            get {
                return ResourceManager.GetString("EnumConditionIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        internal static string EnumConditionIsNotEqualTo {
            get {
                return ResourceManager.GetString("EnumConditionIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        internal static string EnumConditionIsNotNull {
            get {
                return ResourceManager.GetString("EnumConditionIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        internal static string EnumConditionIsNull {
            get {
                return ResourceManager.GetString("EnumConditionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string FilterManagerApply {
            get {
                return ResourceManager.GetString("FilterManagerApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string FilterManagerClear {
            get {
                return ResourceManager.GetString("FilterManagerClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string FilterManagerClose {
            get {
                return ResourceManager.GetString("FilterManagerClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        internal static string NumberConditionIsEqualTo {
            get {
                return ResourceManager.GetString("NumberConditionIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than.
        /// </summary>
        internal static string NumberConditionIsGreaterThan {
            get {
                return ResourceManager.GetString("NumberConditionIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than or equal to.
        /// </summary>
        internal static string NumberConditionIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("NumberConditionIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than.
        /// </summary>
        internal static string NumberConditionIsLessThan {
            get {
                return ResourceManager.GetString("NumberConditionIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than or equal to.
        /// </summary>
        internal static string NumberConditionIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("NumberConditionIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        internal static string NumberConditionIsnotEqualTo {
            get {
                return ResourceManager.GetString("NumberConditionIsnotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        internal static string NumberConditionIsNotNull {
            get {
                return ResourceManager.GetString("NumberConditionIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        internal static string NumberConditionIsNull {
            get {
                return ResourceManager.GetString("NumberConditionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string PagerFirst {
            get {
                return ResourceManager.GetString("PagerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string PagerLast {
            get {
                return ResourceManager.GetString("PagerLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string PagerNext {
            get {
                return ResourceManager.GetString("PagerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PagerPrevious {
            get {
                return ResourceManager.GetString("PagerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string StringConditionContains {
            get {
                return ResourceManager.GetString("StringConditionContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contain.
        /// </summary>
        internal static string StringConditionDoesNotContain {
            get {
                return ResourceManager.GetString("StringConditionDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        internal static string StringConditionEndsWith {
            get {
                return ResourceManager.GetString("StringConditionEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        internal static string StringConditionIsEqualTo {
            get {
                return ResourceManager.GetString("StringConditionIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        internal static string StringConditionIsNotEqualTo {
            get {
                return ResourceManager.GetString("StringConditionIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null or empty.
        /// </summary>
        internal static string StringConditionIsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("StringConditionIsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null or empty.
        /// </summary>
        internal static string StringConditionIsNullOrEmpty {
            get {
                return ResourceManager.GetString("StringConditionIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        internal static string StringConditionStartsWith {
            get {
                return ResourceManager.GetString("StringConditionStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details View.
        /// </summary>
        internal static string TableDetailsView {
            get {
                return ResourceManager.GetString("TableDetailsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Search....
        /// </summary>
        internal static string TableGlobalSearch {
            get {
                return ResourceManager.GetString("TableGlobalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string TableLoading {
            get {
                return ResourceManager.GetString("TableLoading", resourceCulture);
            }
        }
    }
}
